// Auto-generated by Supabase — do not edit by hand.
// Regenerate: npx supabase gen types typescript --project-id vwwcswmqfqclosengqce > lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      exercise_sets: {
        Row: {
          completed_at: string
          id: string
          prescribed_reps: string | null
          prescribed_weight_kg: number | null
          reps_completed: number | null
          rpe: number | null
          session_id: string
          set_number: number
          weight_kg_used: number | null
          workout_exercise_id: string
        }
        Insert: {
          completed_at?: string
          id?: string
          prescribed_reps?: string | null
          prescribed_weight_kg?: number | null
          reps_completed?: number | null
          rpe?: number | null
          session_id: string
          set_number: number
          weight_kg_used?: number | null
          workout_exercise_id: string
        }
        Update: {
          completed_at?: string
          id?: string
          prescribed_reps?: string | null
          prescribed_weight_kg?: number | null
          reps_completed?: number | null
          rpe?: number | null
          session_id?: string
          set_number?: number
          weight_kg_used?: number | null
          workout_exercise_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "exercise_sets_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "workout_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "exercise_sets_workout_exercise_id_fkey"
            columns: ["workout_exercise_id"]
            isOneToOne: false
            referencedRelation: "workout_exercises"
            referencedColumns: ["id"]
          },
        ]
      }
      exercises: {
        Row: {
          category: string
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          image_url: string | null
          muscle_group: string | null
          name: string
          updated_at: string
          uses_reps: boolean
          uses_weight: boolean
          video_url: string | null
        }
        Insert: {
          category: string
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          muscle_group?: string | null
          name: string
          updated_at?: string
          uses_reps?: boolean
          uses_weight?: boolean
          video_url?: string | null
        }
        Update: {
          category?: string
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          muscle_group?: string | null
          name?: string
          updated_at?: string
          uses_reps?: boolean
          uses_weight?: boolean
          video_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "exercises_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string
          display_name: string
          id: string
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name: string
          id?: string
          role: Database["public"]["Enums"]["user_role"]
          updated_at?: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
          username?: string
        }
        Relationships: []
      }
      pt_clients: {
        Row: {
          client_id: string
          created_at: string
          ended_at: string | null
          id: string
          notes: string | null
          pt_id: string
          started_at: string
          status: Database["public"]["Enums"]["relationship_status"]
          updated_at: string
        }
        Insert: {
          client_id: string
          created_at?: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          pt_id: string
          started_at?: string
          status?: Database["public"]["Enums"]["relationship_status"]
          updated_at?: string
        }
        Update: {
          client_id?: string
          created_at?: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          pt_id?: string
          started_at?: string
          status?: Database["public"]["Enums"]["relationship_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "pt_clients_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pt_clients_pt_id_fkey"
            columns: ["pt_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      scheduled_workouts: {
        Row: {
          assigned_by_pt_id: string
          client_id: string
          created_at: string
          id: string
          notes_for_client: string | null
          scheduled_date: string
          status: Database["public"]["Enums"]["scheduled_status"]
          updated_at: string
          workout_id: string
        }
        Insert: {
          assigned_by_pt_id: string
          client_id: string
          created_at?: string
          id?: string
          notes_for_client?: string | null
          scheduled_date: string
          status?: Database["public"]["Enums"]["scheduled_status"]
          updated_at?: string
          workout_id: string
        }
        Update: {
          assigned_by_pt_id?: string
          client_id?: string
          created_at?: string
          id?: string
          notes_for_client?: string | null
          scheduled_date?: string
          status?: Database["public"]["Enums"]["scheduled_status"]
          updated_at?: string
          workout_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scheduled_workouts_assigned_by_pt_id_fkey"
            columns: ["assigned_by_pt_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scheduled_workouts_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scheduled_workouts_workout_id_fkey"
            columns: ["workout_id"]
            isOneToOne: false
            referencedRelation: "workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      workout_exercises: {
        Row: {
          created_at: string
          exercise_id: string
          id: string
          notes: string | null
          position: number
          prescription: string
          rest_seconds: number
          sets: number
          weight_kg: number | null
          workout_id: string
        }
        Insert: {
          created_at?: string
          exercise_id: string
          id?: string
          notes?: string | null
          position: number
          prescription: string
          rest_seconds?: number
          sets: number
          weight_kg?: number | null
          workout_id: string
        }
        Update: {
          created_at?: string
          exercise_id?: string
          id?: string
          notes?: string | null
          position?: number
          prescription?: string
          rest_seconds?: number
          sets?: number
          weight_kg?: number | null
          workout_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_exercises_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_exercises_workout_id_fkey"
            columns: ["workout_id"]
            isOneToOne: false
            referencedRelation: "workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      workout_sessions: {
        Row: {
          client_id: string
          completed_at: string | null
          created_at: string
          duration_seconds: number | null
          id: string
          notes: string | null
          scheduled_workout_id: string
          started_at: string
          updated_at: string
        }
        Insert: {
          client_id: string
          completed_at?: string | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          notes?: string | null
          scheduled_workout_id: string
          started_at?: string
          updated_at?: string
        }
        Update: {
          client_id?: string
          completed_at?: string | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          notes?: string | null
          scheduled_workout_id?: string
          started_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_sessions_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_sessions_scheduled_workout_id_fkey"
            columns: ["scheduled_workout_id"]
            isOneToOne: false
            referencedRelation: "scheduled_workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      workouts: {
        Row: {
          category: string
          created_at: string
          deleted_at: string | null
          description: string | null
          difficulty: Database["public"]["Enums"]["difficulty_level"]
          estimated_calories: number | null
          estimated_duration_minutes: number | null
          id: string
          image_url: string | null
          pt_id: string
          title: string
          updated_at: string
        }
        Insert: {
          category: string
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          difficulty?: Database["public"]["Enums"]["difficulty_level"]
          estimated_calories?: number | null
          estimated_duration_minutes?: number | null
          id?: string
          image_url?: string | null
          pt_id: string
          title: string
          updated_at?: string
        }
        Update: {
          category?: string
          created_at?: string
          deleted_at?: string | null
          description?: string | null
          difficulty?: Database["public"]["Enums"]["difficulty_level"]
          estimated_calories?: number | null
          estimated_duration_minutes?: number | null
          id?: string
          image_url?: string | null
          pt_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workouts_pt_id_fkey"
            columns: ["pt_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      difficulty_level: "beginner" | "intermediate" | "advanced"
      relationship_status: "active" | "paused" | "ended"
      scheduled_status: "scheduled" | "completed" | "missed" | "skipped"
      user_role: "pt" | "client"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// ── Convenience aliases used throughout the app ──────────────────────────────
// These re-export the enum types so existing imports keep working.
export type UserRole = Database["public"]["Enums"]["user_role"]
export type DifficultyLevel = Database["public"]["Enums"]["difficulty_level"]
export type RelationshipStatus = Database["public"]["Enums"]["relationship_status"]
export type ScheduledStatus = Database["public"]["Enums"]["scheduled_status"]

// ── Supabase helper types ────────────────────────────────────────────────────
type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  TableName extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]),
> = (DefaultSchema["Tables"] &
  DefaultSchema["Views"])[TableName] extends { Row: infer R }
  ? R
  : never

export type TablesInsert<
  TableName extends keyof DefaultSchema["Tables"],
> = DefaultSchema["Tables"][TableName] extends { Insert: infer I } ? I : never

export type TablesUpdate<
  TableName extends keyof DefaultSchema["Tables"],
> = DefaultSchema["Tables"][TableName] extends { Update: infer U } ? U : never

export type Enums<
  EnumName extends keyof DefaultSchema["Enums"],
> = DefaultSchema["Enums"][EnumName]
